//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ngohoangminh_2210900044Entities : DbContext
    {
        public ngohoangminh_2210900044Entities()
            : base("name=ngohoangminh_2210900044Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nhm_SACH> nhm_SACH { get; set; }
        public virtual DbSet<nhm_TACGIA> nhm_TACGIA { get; set; }
    }
}
